### ISSUE TITLE
던전 입장시 "입장 " 입력시 서버 다운되는 현상 있습니다.

### ISSUE THREAD

**Issue by JangKroed** [Hanghae-GREATGREAT/MUD#26]
"입장" 까지만 입력하면 에러를 잡는데 뒤에 공백이 들어가면 서버가 다운되는 현상이 있는데,
.trim()을 이용하여 잡아주면 좋을것 같습니다 !

**Comment by ninthsun91** [comment]
확인

**Comment by ninthsun91** [comment]
애초에 trim()이 전부 붙어있고, 해당 문제 확인이 안됩니다. 일단 보류
